name: monitoring-system
services:
  backend:
    build:
      context: ./monitoring-system-server
      dockerfile: Dockerfile
    ports:
      - 42068:42068
    volumes:
      - ./monitoring-system-server/db:/db
  data-visualization:
    build:
      context: ./monitoring-data-analysis
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_started
        
